---
# tasks file for jenkins
- name: add jenkins persistent volume
  k8s:
    state: present
    kubeconfig: "{{ kube_config }}"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: jenkins-pv-volume
        namespace: tools
        labels:
          type: local
      spec:
        storageClassName: manual
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: "/tmp/data"

- name: add jenkins persistent volume claim
  k8s:
    state: present
    kubeconfig: "{{ kube_config }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: jenkins-pv-claim
        namespace: tools
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

- name: add jenkins deployment
  k8s:
    state: present
    kubeconfig: "{{ kube_config }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jenkins
        namespace: tools
        labels:
          app: jenkins
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: jenkins
        template:
          metadata:
            labels:
              app: jenkins
          spec:
            containers:
            - name: jenkins
              image: ahmedemad2051/jenkins-ansible:latest
              ports:
              - containerPort: 8080
              volumeMounts:
              - name: docker-sock
                mountPath: /var/run/docker.sock
              - name: docker-command
                mountPath: /usr/bin/docker
              # - name: jenkins-pv-storage
                # mountPath: /var/jenkins_home/
            securityContext:
             fsGroup: 1950
            volumes:
            - name: docker-sock
              hostPath:
                path: /var/run/docker.sock
            - name: docker-command
              hostPath:
                path: /usr/bin/docker
            - name: jenkins-pv-storage
              persistentVolumeClaim:
                claimName: jenkins-pv-claim

- name: add jenkins service
  k8s:
    state: present
    kubeconfig: "{{ kube_config }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: jenkins-svc
        namespace: tools
        labels:
          app: jenkins
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 8080
        selector:
          app: jenkins
