---
# tasks file for nexus
- name: add nexus deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nexus
        namespace: tools
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nexus
        template:
          metadata:
            labels:
              app: nexus
          spec:
            containers:
              - name: nexus
                image: sonatype/nexus3:latest
                ports:
                  - containerPort: 8081
                volumeMounts:
                  - name: nexus-data
                    mountPath: /nexus-data
            volumes:
              - name: nexus-data
                emptyDir: {}

- name: add nexus service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nexus
        namespace: tools
      spec:
        selector:
          app: nexus
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 8081
