pipeline {
   agent any
   stages {
       stage('Build') {
           agent {
               docker {
                   image 'python:3.6.8'
                   args  '--net="host"'
               }
           }
           steps {
              sh 'pip3 install redis --user'
           }
       }




   }
}
