pipeline{
    agent { docker {
      image 'python:3.7.2'
      args  '--net="host"'
     } }
    stages{
        stage('build') {
            steps {
                sh 'python3 -m venv env'
                sh 'source ./env/bin/activate'
                sh 'python -m pip install redis --user'

            }
        }
    }



}
