pipeline{
    agent { docker {
      image 'python:3.7.2'
      args  '--net="bridge"'
     } }
    stages{
        stage('build') {
            steps {
                sh 'pip install  -r app/requirements.txt --user'

            }
        }
    }



}
