
- hosts: localhost
  tasks:
  - name: App Deployment
    k8s:
      state: present
      kubeconfig: "/var/jenkins_home/.kube/config"
      namespace: tools
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: app
          labels:
            name: app
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: app
          template:
            metadata:
              labels:
                name: app
            spec:
              containers:
              - name: app
                image: '{{image}}'
  - name: App Service
    k8s:
      state: present
      kubeconfig: "/var/jenkins_home/.kube/config"
      namespace: tools
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: app
        spec:
          type: LoadBalancer
          selector:
            name: app
          ports:
            - port: 80
              targetPort: 8080
