---
# tasks file for sonarQube
- name: add sonarQube deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
       name: sonarqube
       namespace: tools
       labels:
          app: sonarqube
      spec:
        selector:
          matchLabels:
           app: sonarqube
        replicas: 1
        template:
          metadata:
            labels:
              app: sonarqube
          spec:
            containers:
            - name: sonarqube
              image: sonarqube:latest
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              ports:
                - containerPort: 9000

- name: add sonarQube service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
          name: sonarqube
          namespace: tools
          labels:
              app: sonarqube
      spec:
          selector:
             app: sonarqube
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 9000
